---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: pulp-celerybeat
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: pulp-celerybeat
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: pulp-celerybeat
    spec:
      containers:
        - name: pulp-celerybeat
          securityContext: {}
          state: present
          image: "{{ registry }}/pulp-celerybeat:latest"
      serviceAccount: anyuid
      serviceAccountName: anyuid
  replicas: 1
  strategy:
    type: Rolling
    rollingParams:
      timeoutSeconds: 900
