---
- name: Scale Candlepin to 0
  openshift_raw:
      name: candlepin
      namespace: "{{ project_name }}"
      replicas: 0
      kind: DeploymentConfig
  tags:
    - stop
    - restart

- name: Create Candlepin deployment
  openshift_raw:
      state: "{{ deployment_state }}"
      force: false
      definition:
          apiVersion: v1
          kind: DeploymentConfig
          metadata:
              name: candlepin
              labels:
                  app: foreman
                  service: candlepin
              namespace: "{{ project_name }}"
          spec:
              replicas: 1
              strategy:
                rollingParams:
                  timeoutSeconds: 900
                type: Rolling
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: candlepin
                  spec:
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
                      containers:
                        - name: candlepin
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: true
                              mountPath: /etc/candlepin/certs
                              name: ca
                          env:
                            - name: POSTGRES_DB
                              value: foreman
                            - name: POSTGRES_USER
                              value: foreman
                            - name: POSTGRES_PASSWORD
                              value: foreman
                            - name: POSTGRES_PORT
                              value: '5432'
                            - name: POSTGRES_SERVICE
                              value: postgres
                            - name: QPID_SERVICE
                              value: qpid
                            - name: QPID_PORT
                              value: '5672'
                          image: "{{ registry }}/candlepin:latest"
                      volumes:
                        - secret:
                              items:
                                - path: candlepin-ca.key
                                  key: ca.key
                                - path: candlepin-ca.crt
                                  key: ca.crt
                              secretName: ca
                          name: ca
  tags:
    - start
    - restart
    - destroy
