---
- name: Create route
  openshift_v1_route:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: Route
          metadata:
              name: foreman-8080
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: foreman
          spec:
              to:
                  kind: Service
                  name: foreman
              port:
                  targetPort: port-8080-tcp
  tags:
    - start
    - destroy
