---
katello_client_cleanup: False
katello_client_organization: "Default_Organization"
katello_client_environment: "Library"
katello_client_username: "admin"
katello_client_password: "changeme"
katello_client_activationkey: ""
katello_client_extra_repos: []
katello_client_install_agent: False
katello_client_install_tracer: False
