---
dependencies:
  - role: selinux
  - role: etc_hosts
  - role: koji
  - role: epel_repositories
  - role: ostree_repositories
  - role: puppet_repositories
  - role: foreman_repositories
  - role: katello_repositories
  - role: foreman_installer
    foreman_installer_scenario: katello
    foreman_installer_options_internal_use_only:
      - "{{ '--disable-system-checks' if katello_repositories_version != '3.1' else '' }}"
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
    foreman_installer_additional_packages:
      - katello
