installers:
  - foreman: '1.15'
    katello: '3.4'
    puppet: 4
    boxes:
      - 'centos7'
      - 'debian8'
      - 'ubuntu1604'

  - foreman: '1.16'
    katello: '3.5'
    puppet: 5
    boxes:
      - 'centos7'
      - 'debian8'
      - 'debian9'
      - 'ubuntu1604'

  - foreman: '1.17'
    katello: '3.6'
    puppet: 5
    boxes:
      - 'centos7'
      - 'debian9'
      - 'ubuntu1604'

  - foreman: '1.18'
    katello: '3.7'
    puppet: 5
    boxes:
      - 'centos7'
      - 'debian9'
      - 'ubuntu1604'

  - foreman: '1.19'
    katello: '3.8'
    puppet: 5
    boxes:
      - 'centos7'
      - 'centos7-fips'
      - 'debian9'
      - 'ubuntu1804'

  - foreman: 'nightly'
    katello: 'nightly'
    puppet: 5
    boxes:
      - 'centos7'
      - 'centos7-fips'
      - 'debian9'
      - 'ubuntu1604'
      - 'ubuntu1804'
