installers:
  - foreman: '2.4'
    katello: '4.0'
    pulp: '2.21'
    pulpcore: '3.9'
    puppet: 6
    boxes:
      - 'centos7'
      - 'centos7-fips'
      - 'centos8'
      - 'debian10'
      - 'ubuntu1804'

  - foreman: '2.5'
    katello: '4.1'
    pulpcore: '3.14'
    puppet: 6
    boxes:
      - 'centos7'
      - 'centos7-fips'
      - 'centos8'
      - 'centos8-stream'
      - 'debian10'
      - 'ubuntu1804'
      - 'ubuntu2004'

  - foreman: '3.0'
    katello: '4.2'
    pulpcore: '3.14'
    puppet: 6
    boxes:
      - 'centos7'
      - 'centos7-fips'
      - 'centos8'
      - 'centos8-stream'
      - 'debian10'
      - 'ubuntu1804'
      - 'ubuntu2004'

  - foreman: '3.1'
    katello: '4.3'
    pulpcore: '3.16'
    puppet: 7
    boxes:
      - 'centos7'
      - 'centos7-fips'
      - 'centos8'
      - 'centos8-stream'
      - 'debian10'
      - 'ubuntu2004'

  - foreman: 'nightly'
    katello: 'nightly'
    pulpcore: '3.16'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos7'
      - 'centos7-fips'
      - 'centos8'
      - 'centos8-stream'
      - 'debian10'
      - 'debian11'
      - 'ubuntu2004'
