installers:
  - foreman: '3.3'
    katello: '4.5'
    pulpcore: '3.18'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos7'
      - 'centos7-fips'
      - 'centos8'
      - 'centos8-stream'
      - 'debian10'
      - 'debian11'
      - 'ubuntu2004'

  - foreman: '3.4'
    katello: '4.6'
    pulpcore: '3.18'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos8-stream'
      - 'debian11'
      - 'ubuntu2004'

  - foreman: '3.5'
    katello: '4.7'
    pulpcore: '3.21'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos8-stream'
      - 'debian11'
      - 'ubuntu2004'

  - foreman: '3.6'
    katello: '4.8'
    pulpcore: '3.22'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos8-stream'
      - 'debian11'
      - 'ubuntu2004'

  - foreman: '3.7'
    katello: '4.9'
    pulpcore: '3.22'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos8-stream'
      - 'debian11'
      - 'ubuntu2004'

  - foreman: '3.8'
    katello: '4.10'
    pulpcore: '3.28'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos8-stream'
      - 'debian11'
      - 'ubuntu2004'

  - foreman: 'nightly'
    katello: 'nightly'
    pulpcore: '3.39'
    puppet: 7
    boxes:
      - 'almalinux8'
      - 'centos8-stream'
      - 'debian11'
      - 'ubuntu2004'
