---
- name: 'Run installer'
  shell: >
      {{ foreman_installer_command }} {{ (foreman_installer_verbose == True) | ternary("-v", "") }}
      --scenario "{{ foreman_installer_scenario }}"
      {{ foreman_installer_options | join(" ") if foreman_installer_options is iterable else '' }}
      {{ foreman_installer_options if foreman_installer_options is string else '' }}
      {{ foreman_installer_options_internal_use_only | join(" ") }}
  when: not foreman_installer_skip_installer
  tags:
    - installation
