---
luna_provisioning_installer_options: []
luna_provisioning_installer_internal_options:
  - "--enable-foreman-cli-discovery"
  - "--enable-foreman-cli-remote-execution"
  - "--enable-foreman-cli-tasks"
  - "--enable-foreman-cli-templates"
  - "--enable-foreman-cli-virt-who-configure"
  - "--enable-foreman-plugin-ansible"
  - "--enable-foreman-plugin-bootdisk"
  - "--enable-foreman-plugin-discovery"
  - "--enable-foreman-plugin-hooks"
  - "--enable-foreman-plugin-remote-execution"
  - "--enable-foreman-plugin-templates"
  - "--enable-foreman-plugin-virt-who-configure"
  - "--enable-foreman-proxy-plugin-ansible"
  - "--enable-foreman-proxy-plugin-discovery"
  - "--enable-foreman-proxy-plugin-remote-execution-ssh"
