- name: 'Install SCL repository'
  yum:
    name: centos-release-scl
    state: present

- name: 'Install Ruby SCL'
  yum:
    name:
      - "{{ ruby_scl_version }}"
      - "{{ ruby_scl_version }}-ruby-devel"
    state: present

- name: 'Enable SCL at login'
  blockinfile:
    dest: /etc/profile.d/enable-{{ ruby_scl_version }}.sh
    create: yes
    block: |
      #!/bin/bash
      source scl_source enable {{ ruby_scl_version }}
