---
- name: 'Set up qpid Copr repository'
  ansible.builtin.yum_repository:
    name: qpid
    description: Copr repo for qpid owned by @qpid
    baseurl: https://download.copr.fedorainfracloud.org/results/@qpid/qpid/epel-{{ ansible_distribution_major_version }}-$basearch/
    state: present
    gpgcheck: yes
    gpgkey: https://download.copr.fedorainfracloud.org/results/@qpid/qpid/pubkey.gpg
