---
- name: 'Setup Foreman {{ foreman_client_repositories_version }} Client Release Repository'
  yum:
    name: https://yum.theforeman.org/client/{{ foreman_client_repositories_version }}/{{ foreman_client_repositories_dists[ansible_os_family] }}{{ ansible_distribution_major_version }}/x86_64/foreman-client-release.rpm
    disable_gpg_check: True
    state: present
