---
# disable ipv6 for issue #12386. qdrouterd only listens on ipv4.
# also, do this before running katello installer so we don't interfere with
# pulp (see https://pulp.plan.io/issues/2586)
- name: "Disable ipv6"
  sysctl:
    name: "{{ item }}"
    value: 1
  with_items:
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.all.disable_ipv6

- name: "Update hosts file"
  shell: "sed -i 's/^[[:space:]]*::/#::/' /etc/hosts"
