---
- name: 'Create certs directory'
  file:
    path: "{{ certificates_ca_directory_certs }}"
    state: directory
    mode: 0755

- name: 'Create keys directory'
  file:
    path: "{{ certificates_ca_directory_keys }}"
    state: directory
    mode: 0755

- name: 'Create requests directory'
  file:
    path: "{{ certificates_ca_directory_requests }}"
    state: directory
    mode: 0755

- name: 'Deploy configuration file'
  template:
    src: openssl.cnf.j2
    dest: "{{ certificates_ca_directory }}/openssl.cnf"
    mode: 0644

- name: 'Create index file'
  file:
    path: "{{ certificates_ca_directory }}/index.txt"
    state: touch
    mode: 0644

- name: 'Ensure serial starting number'
  template:
    src: serial.j2
    dest: "{{ certificates_ca_directory }}/serial"
    force: no
    mode: 0644

- name: 'Creating CA certificate and key'
  command: >
    openssl req -new
      -x509
      -nodes
      -extensions v3_ca
      -days 7300
      -config "{{ certificates_ca_directory }}/openssl.cnf"
      -keyout "{{ certificates_ca_directory_keys }}/ca.key"
      -out "{{ certificates_ca_directory_certs }}/ca.crt"
  args:
    creates: "{{ certificates_ca_directory_certs }}/ca.crt"
