---
- name: 'Clone bats'
  git:
    repo: https://github.com/katello/forklift.git
    dest: /root/forklift

- name: 'Install bats'
  shell: /root/forklift/bats/bootstrap.sh

- name: 'Run bats'
  shell: /usr/local/bin/katello-bats content proxy
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
