---
- name: 'Remove katello-repos'
  ansible.builtin.yum:
    name: katello-repos
    state: absent

- name: 'Katello {{ katello_repositories_version }} Koji repository'
  ansible.builtin.yum_repository:
    name: katello-koji
    description: "Katello {{ katello_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/katello/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: '1'
    gpgcheck: no

- name: 'Candlepin Koji repository'
  ansible.builtin.yum_repository:
    name: candlepin-koji
    description: "Candlepin {{ katello_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/candlepin/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: '1'
    gpgcheck: no

- name: 'Set module_hotfixes=1'
  ansible.builtin.lineinfile:
    path: "/etc/yum.repos.d/{{ item }}.repo"
    line: module_hotfixes=1
  loop:
    - katello-koji
    - candlepin-koji
  when:
    - katello_repositories_version != 'nightly'
    - katello_repositories_version is version('4.2', '<=')

- name: 'Enable katello:el8 module'
  ansible.builtin.command: dnf module enable -y katello:el8
  # can't use the `dnf` module for modules without a default stream
  # https://github.com/ansible/ansible/issues/56504
  # https://github.com/ansible/ansible/issues/64852
  args:
    warn: False
    creates: /etc/dnf/modules.d/katello.module
  when:
    - katello_repositories_version == "nightly" or katello_repositories_version is version('4.4', '>=')
    - ansible_distribution_major_version == '8'

- name: 'Add Pulpcore repository'
  ansible.builtin.include_role:
    name: pulpcore_repositories
