---
- name: 'Remove katello-repos'
  yum:
    name: katello-repos
    state: absent

- name: 'Katello {{ katello_repositories_version }} Koji repository'
  yum_repository:
    name: katello-koji
    description: "Katello {{ katello_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/katello/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: '1'
    gpgcheck: no

- name: 'Candlepin Koji repository'
  yum_repository:
    name: candlepin-koji
    description: "Candlepin {{ katello_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/katello-{{ katello_repositories_version }}/candlepin/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: '1'
    gpgcheck: no

- name: 'Set module_hotfixes=1'
  lineinfile:
    path: "/etc/yum.repos.d/{{ item }}.repo"
    line: module_hotfixes=1
  loop:
    - katello-koji
    - candlepin-koji

- name: 'Add Pulp {{ katello_repositories_pulp_version }} Stable repository'
  yum_repository:
    name: pulp-repository
    description: Pulp release repository
    baseurl: "https://repos.fedorapeople.org/repos/pulp/pulp/{{ katello_repositories_pulp_release }}/{{ katello_repositories_pulp_version }}/$releasever/$basearch"
    gpgcheck: no
    enabled: yes
  when:
    - katello_repositories_version != "nightly"
    - katello_repositories_version is version('4.0', '<=')
    - katello_repositories_pulp_version != "nightly"
    - ansible_distribution_major_version == '7'

- name: Add Pulp Nightly repository
  yum_repository:
    name: pulp-repository
    description: Pulp nightly repository
    baseurl: "https://repos.fedorapeople.org/repos/pulp/pulp/testing/automation/2-master/stage/$releasever/$basearch"
    gpgcheck: no
    enabled: yes
  when:
    - katello_repositories_version != "nightly"
    - katello_repositories_version is version('4.0', '<=')
    - katello_repositories_pulp_version == "nightly"
    - ansible_distribution_major_version == '7'

- name: 'Add Pulpcore repository'
  include_role:
    name: pulpcore_repositories
