---
apiVersion: v1
kind: Route
metadata:
  name: foreman-http-pub
  namespace: "{{ project_name }}"
  labels:
    app: httpd
spec:
  host: "{{ application_hostname }}"
  path: /pub
  to:
    kind: Service
    name: httpd
  port:
    targetPort: http
