---
- name: Login as system admin
  command: oc login -u system:admin
  when: minishift
  tags:
    - start

- name: Add anyuid scc to anyuid service account
  command: oc adm policy add-scc-to-user anyuid system:serviceaccount:{{ project_name }}:anyuid
  tags:
    - start

- name: Login as developer
  command: oc login -u developer -p a
  when: minishift
  tags:
    - start

- name: Create anyuid service account
  k8s_v1_service_account:
    state: present
    force: false
    resource_definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: anyuid
        namespace: "{{ project_name }}"
  tags:
    - start
