---
- name: Create PVC
  k8s_v1_persistent_volume_claim:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
              name: puppet-data
              namespace: "{{ project_name }}"
          spec:
              resources:
                  requests:
                      storage: 1Gi
              accessModes:
                - ReadWriteOnce
  tags:
    - start
    - destroy
- name: Create PVC
  k8s_v1_persistent_volume_claim:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
              name: mongodb-data
              namespace: "{{ project_name }}"
          spec:
              resources:
                  requests:
                      storage: 1Gi
              accessModes:
                - ReadWriteOnce
  tags:
    - start
    - destroy
- name: Create PVC
  k8s_v1_persistent_volume_claim:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
              name: pulp-data
              namespace: "{{ project_name }}"
          spec:
              resources:
                  requests:
                      storage: 1Gi
              accessModes:
                - ReadWriteOnce
  tags:
    - start
    - destroy
