---
foreman_seeder_hosts_hammer: hammer
foreman_seeder_hosts_use_taxonomies: False
foreman_seeder_hosts_organization: Default Organization
foreman_seeder_hosts_location: Default Location
foreman_seeder_hosts:
  - name: host1
    hostgroup: Forklift CentOS 7
  - name: host2
    hostgroup: Forklift Fedora 25
  - name: host3
    hostgroup: Forklift Debian 8.7
  - name: host4
    hostgroup: Forklift Ubuntu 16.04

