---
server_group: "server-{{ inventory_hostname }}"
katello_server_origin: "{{ groups[server_group][0] }}"
katello_server: "{{ katello_server_origin.replace('centos','c') }}"
katello_server_ip: "{{hostvars[katello_server_origin]['ansible_ssh_host']}}"

freeipa_server_ip: "{{ ansible_eth0.ipv4.address }}"
freeipa_server_realm: "{{ ansible_domain | upper }}"
freeipa_server_domain: "{{ ansible_domain }}"
freeipa_server_directory_manager_password: "changeme"
freeipa_server_directory_admin_password: "changeme"
freeipa_server_kerberos_principal: "admin"
freeipa_server_realm_password: "changeme"
