---
- name: 'Remove foreman-release'
  yum:
    name: foreman-release
    state: absent

- name: 'Foreman Koji repository'
  yum_repository:
    name: foreman-koji
    description: "Foreman {{ foreman_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/foreman-{{ foreman_version }}/RHEL/{{ release }}/x86_64/"
    priority: 1
    gpgcheck: 0

- name: 'Foreman Plugins Koji repository'
  yum_repository:
    name: foreman-plugins-koji
    description: "Foreman Plugins {{ foreman_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/foreman-plugins-{{ foreman_version }}/RHEL/{{ release }}/x86_64/"
    priority: 1
    gpgcheck: 0
