---
foreman_server_repositories_katello: true
foreman_server_repositories_ostree: true
foreman_installer_scenario: katello
foreman_installer_options_internal_use_only:
  - --disable-system-checks
  - "--foreman-initial-admin-password {{ foreman_installer_admin_password }}"
foreman_installer_additional_packages:
  - katello
