---
katello_repositories_version: nightly
katello_repositories_environment: "{{ foreman_repositories_environment | default('release') }}"
katello_repositories_pulp_version: 2.18
katello_repositories_pulp_release: beta
