---
- name: 'Install koji package'
  yum:
    name: 'koji'
    state: 'present'

- name: 'Make repo directory'
  file:
    path: '{{ koji_repo_directory }}'
    state: 'directory'

- name: 'Download RPMs'
  command: "koji --server {{ koji_host }} download-task --topurl {{ koji_topurl }} {{ item }}"
  args:
    chdir: "{{ koji_repo_directory }}"
  with_items: "{{ koji_task_ids }}"

- name: 'Install createrepo'
  yum:
    name: 'createrepo'
    state: 'present'

- name: 'Create repo'
  command: "createrepo {{ koji_repo_directory }}"

- name: 'Add repo file'
  yum_repository:
    name: "koji-forklift-task-repo"
    description: 'Local repository for Koji task RPMs'
    baseurl: "file://{{ koji_repo_directory }}"
    file: "koji_forklift_task_repo"
    priority: 1
    enabled: yes
    gpgcheck: no
