---
- name: Scale Puppet to 0
  openshift_v1_deployment_config:
      name: puppet
      namespace: "{{ project_name }}"
      replicas: 0
  tags:
    - stop
    - restart

- name: Create Puppet deployment
  openshift_v1_deployment_config:
      state: "{{ deployment_state }}"
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: puppet
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: puppet
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: puppet
                  spec:
                      containers:
                        - name: puppet
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: false
                              mountPath: /etc/puppet
                              name: puppet-data
                          image: puppet/puppetserver
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
                      volumes:
                        - name: puppet-data
                          persistentVolumeClaim:
                              claimName: puppet-data
              replicas: 1
              strategy:
                  type: Rolling
                  rollingParams:
                      timeoutSeconds: 900
  tags:
    - start
    - restart
    - destroy
