---
- name: Stop running containers by scaling replicas down to 0
  openshift_v1_deployment_config:
      state: present
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: puppet
              labels:
                  app: foreman
                  service: puppet
              namespace: foreman
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: puppet
                  spec:
                      containers:
                        - name: puppet
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: false
                              mountPath: /etc/puppet
                              name: puppet-data
                          image: puppet/puppetserver
                      volumes:
                        - name: puppet-data
                          persistentVolumeClaim:
                              claimName: puppet-data
              replicas: 0
              strategy:
                  type: Rolling
  tags:
    - stop
    - restart
- name: Create deployment, and scale replicas up
  openshift_v1_deployment_config:
      state: present
      force: false
      resource_definition:
          apiVersion: v1
          kind: deployment_config
          metadata:
              name: puppet
              labels:
                  app: foreman
                  service: puppet
              namespace: foreman
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: puppet
                  spec:
                      containers:
                        - name: puppet
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: false
                              mountPath: /etc/puppet
                              name: puppet-data
                          image: puppet/puppetserver
                      volumes:
                        - name: puppet-data
                          persistentVolumeClaim:
                              claimName: puppet-data
              replicas: 1
              strategy:
                  type: Rolling
  tags:
    - start
    - restart
