:katello:
  :rest_client_timeout: 3600

  :post_sync_url: http://<%= ENV['FOREMAN_SERVICE_HOST'] || 'foreman' %>:8080/katello/api/v2/repositories/sync_complete?token=MEJ8UiYrjYE4V6Q2vPuxs7k4iz9cDpDq

  :candlepin:
    # Default to candlepin-app due to replacement here -- https://github.com/Katello/katello/blob/master/app/lib/katello/resources/candlepin.rb#L48
    :url: http://<%= ENV['CANDLEPIN_SERVICE_HOST'] || 'cp-app' %>:8080/candlepin
    :oauth_key: katello
    :oauth_secret: katello

  :pulp:
    :url: http://admin:admin@<%= ENV['PULP_SERVICE_HOST'] || 'pulp' %>:<%= ENV['PULP_SERVICE_PORT'] || 8080 %>/pulp/api/v2/
    :basic_auth:
      :user: admin
      :password: admin

  :qpid:
    :url: amqp:tcp:<%= ENV['QPID_SERVICE_HOST'] || 'qpid' %>:5672
    :subscriptions_queue_address: katello_event_queue

  :loggers:
    :pulp_rest:
      :enabled: true
