---
- name: foreman proxy service
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.service.yaml') | from_yaml }}"
  with_items:
    - foreman-proxy

- name: foreman proxy deployment
  k8s:
    state: "{{ deployment_state }}"
    definition: "{{ lookup('template', 'templates/' + item + '.deployment.yaml') | from_yaml }}"
  with_items:
    - foreman-proxy
