---
sosreport_fetch: true
sosreport_output_dir: '/root'
sosreport_local_dir: "/tmp/debug-{{ pipeline_type | default('foreman') }}-{{ pipeline_version | default('nightly') }}-{{ pipeline_os | default('el7') }}"
