shells:
  install_shell: &install_shell
    shell: 'yum -y install ruby && cd /vagrant && ./setup.rb'
  bats_shell: &bats_shell
    shell: '/vagrant/bats/bootstrap_vagrant.sh'
  runcible_shell: &runcible_shell
    shell: '/vagrant/shells/runcible.sh'

boxes:
  centos6:
    box_name:   'centos6'
    image_name: !ruby/regexp '/CentOS 6.*PV/'
    default:    true
    pty:        true
    virtualbox: 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.6_chef-provisionerless.box'
    libvirt:    'http://m0dlx.com/files/foreman/boxes/centos64.box'

  centos7:
    box_name:   'centos7_1'
    image_name: !ruby/regexp '/CentOS 7.*PV/'
    default:    true
    pty:        true
    virtualbox: 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box'
    libvirt:    'https://download.gluster.org/pub/gluster/purpleidea/vagrant/centos-7.1/centos-7.1.box'

  centos6-foreman-nightly:
    box: centos6
    <<: *install_shell
    options: --scenario=foreman

  centos7-foreman-nightly:
    box: centos7
    <<: *install_shell
    options: --scenario=foreman

  centos6-katello-nightly:
    box: centos6
    <<: *install_shell
    options: --scenario=katello

  centos6-capsule-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos6-katello-nightly'

  centos7-katello-nightly:
    box: centos7
    <<: *install_shell
    options: --scenario=katello --disable-selinux
    ansible:
      group: 'server'

  centos7-capsule-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos7-katello-nightly'

  centos6-bats:
    box: centos6
    <<: *bats_shell

  centos7-bats:
    box: centos7
    <<: *bats_shell

  runcible:
    box: centos7
    <<: *runcible_shell
    privileged: false
