shells:
  install_shell: &install_shell
    shell: 'yum -y install ruby && cd /vagrant && ./setup.rb'
  bats_shell: &bats_shell
    shell: '/vagrant/bats/bootstrap_vagrant.sh'
  runcible_shell: &runcible_shell
    shell: '/vagrant/shells/runcible.sh'

boxes:
  centos6:
    box_name:   'centos6'
    image_name: !ruby/regexp '/CentOS 6.*PV/'
    default:    true
    pty:        true
    virtualbox: 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_centos-6.6_chef-provisionerless.box'
    libvirt:    'http://m0dlx.com/files/foreman/boxes/centos64.box'

  centos7:
    box_name:   'centos7_1'
    image_name: !ruby/regexp '/CentOS 7.*PV/'
    default:    true
    pty:        true
    virtualbox: 'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.1_chef-provisionerless.box'
    libvirt:    'https://download.gluster.org/pub/gluster/purpleidea/vagrant/centos-7.1/centos-7.1.box'

  centos7-atomic:
    box_name: centos7-atomic
    pty: true
    libvirt: http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-Vagrant-Libvirt.box

  centos6-foreman-nightly:
    box: centos6
    <<: *install_shell
    options: --scenario=foreman

  centos7-foreman-nightly:
    box: centos7
    <<: *install_shell
    options: --scenario=foreman

  centos6-katello-nightly:
    box: centos6
    <<: *install_shell
    options: --scenario=katello

  centos6-katello-p4-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/katello.yml'
      group: 'server'
      variables:
        puppet_repositories_version: 4

  centos6-capsule-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos6-katello-nightly'

  centos6-capsule-p4-nightly:
    box: centos6
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos6-katello-p4-nightly'
      variables:
        puppet_repositories_version: 4

  centos7-katello-nightly:
    box: centos7
    <<: *install_shell
    options: --scenario=katello --disable-selinux
    ansible:
      group: 'server'

  centos7-provision-nightly:
    box: centos7
    memory: 8096
    ansible:
      playbook:
          - 'playbooks/katello.yml'
          - 'playbooks/katello_provisioning.yml'
      group: 'server'
      variables:
        puppet_repositories_version: 4

  centos7-katello-p4-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/katello.yml'
      group: 'server'
      variables:
        puppet_repositories_version: 4

  centos7-capsule-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos7-katello-nightly'

  centos7-capsule-p4-nightly:
    box: centos7
    ansible:
      playbook: 'playbooks/capsule.yml'
      group: 'capsule'
      server: 'centos7-katello-p4-nightly'
      variables:
        puppet_repositories_version: 4

  centos7-freeipa-server:
      box: centos7
      memory: 2048
      ansible:
        playbook: 'playbooks/freeipa_server.yml'
        group: 'freeipa_server'
        server: 'centos7-katello-nightly'

  centos6-bats:
    box: centos6
    <<: *bats_shell

  centos7-bats:
    box: centos7
    <<: *bats_shell

  runcible:
    box: centos7
    <<: *runcible_shell
    privileged: false

  pipeline-katello-centos7:
    box: centos7
    memory: 4680

  pipeline-capsule-centos7:
    box: centos7
    memory: 3072

  pipeline-katello-3.1-centos7:
    box: centos7
    memory: 4680

  pipeline-capsule-3.1-centos7:
    box: centos7
    memory: 3072

  centos7-hammer-devel:
    box: centos7
    memory: 512
    ansible:
      playbook: 'playbooks/hammer_devel.yml'
      group: 'hammer_devel'
