shells:
  runcible_shell: &runcible_shell
    shell: '/vagrant/shells/runcible.sh'

boxes:
  centos6:
    box_name:   'centos/6'
    image_name: !ruby/regexp '/CentOS 6.*PV/'
    default:    true
    pty:        true

  centos7:
    box_name:   'centos/7'
    image_name: !ruby/regexp '/CentOS 7.*PV/'
    default:    true
    pty:        true

  centos7-atomic:
    box_name: centos7-atomic
    pty: true
    libvirt: http://cloud.centos.org/centos/7/atomic/images/CentOS-Atomic-Host-7-Vagrant-Libvirt.box

  centos7-provision-nightly:
    box: centos7
    memory: 8096
    ansible:
      playbook:
          - 'playbooks/katello.yml'
          - 'playbooks/katello_provisioning.yml'
      group: 'server'

  centos7-freeipa-server:
      box: centos7
      memory: 2048
      ansible:
        playbook: 'playbooks/freeipa_server.yml'
        group: 'freeipa_server'
        server: 'centos7-katello-nightly'

  centos6-bats:
    box: centos6
    ansible:
      playbook: 'playbooks/bats_pipeline_nightly.yml'
      group: 'bats'

  centos7-bats:
    box: centos7
    ansible:
      playbook: 'playbooks/bats_pipeline_nightly.yml'
      group: 'bats'

  runcible:
    box: centos7
    <<: *runcible_shell
    privileged: false

  pipeline-katello-centos7:
    box: centos7
    memory: 4680

  pipeline-proxy-centos7:
    box: centos7
    memory: 3072

  pipeline-katello-3.0-centos7:
    box: centos7
    memory: 4680

  pipeline-proxy-3.0-centos7:
    box: centos7
    memory: 3072

  pipeline-katello-3.1-centos7:
    box: centos7
    memory: 4680

  pipeline-proxy-3.1-centos7:
    box: centos7
    memory: 3072

  pipeline-katello-3.2-centos7:
    box: centos7
    memory: 4680

  pipeline-proxy-3.2-centos7:
    box: centos7
    memory: 3072
  
  pipeline-katello-3.2-centos6:
    box: centos6
    memory: 4680

  pipeline-proxy-3.2-centos6:
    box: centos6
    memory: 3072
  
  pipeline-katello-3.3-centos7:
    box: centos7
    memory: 4680

  pipeline-proxy-3.3-centos7:
    box: centos7
    memory: 3072
