installers:
  - foreman: '1.15'
    katello: '3.4'
    puppet: 4
    boxes:
      - 'centos7'
      - 'debian8'
      - 'ubuntu1604'

  - foreman: '1.16'
    katello: '3.5'
    puppet: 4
    boxes:
      - 'centos7'
      - 'debian8'
      - 'debian9'
      - 'ubuntu1604'

  - foreman: 'nightly'
    katello: 'nightly'
    puppet: 4
    boxes:
      - 'centos7'
      - 'debian8'
      - 'debian9'
      - 'ubuntu1604'
