---
- include_tasks: "{{ ansible_os_family|lower }}_{{ foreman_repositories_environment }}_repos.yml"

- name: 'Install centos-release-scl-rh'
  yum:
    name: centos-release-scl-rh
    state: latest
    update_cache: yes
  tags:
    - packages
  when:
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'

- name: 'Clean yum'
  command: 'yum clean all'
  args:
    warn: false
  tags:
    - packages
  when: ansible_os_family == 'RedHat'
