---
dependencies:
  - role: umask
  - role: selinux
  - role: myhostname
  - role: rackspace_hostname
  - role: etc_hosts
  - role: epel_repositories
  - role: haveged
  - role: puppet_repositories
  - role: foreman_repositories
  - role: foreman_installer
