:foreman:
  # Enable/disable foreman commands
  :enable_module: true

  # Your foreman server address
  :host: http://foreman-foreman-platform.192.168.1.32.xip.io/

  # Credentials. You'll be asked for them interactively if you leave them blank here
  :username: 'admin'
  #:password: 'example'
  :use_sessions: false

  # Check API documentation cache status on each request
  #:refresh_cache: false

  # API request timeout. Set to -1 for no timeout
  #:request_timeout: 120 #seconds

  # Follow API redirects. One of :never, :default, :always
  # Value :default means RestClient default behaviour - follow only in GET and HEAD requests
  #:follow_redirects: :never
