---
apiVersion: batch/v1
kind: Job
metadata:
  name: certificates
  namespace: "{{ project_name }}"
  labels:
    app: certificates
spec:
  template:
    metadata:
      labels:
        app: certificates
    spec:
      restartPolicy: Never
      serviceAccount: "{{ project_name }}-anyuid"
      serviceAccountName: "{{ project_name }}-anyuid"
      containers:
        - name: certificates
          image: "{{ registry }}/certificates:latest"
          command:
            - ansible-playbook
          args:
            - build.yml
            - deploy.yml
          volumeMounts:
            - readOnly: false
              mountPath: /var/www/html/pub/
              name: pub-data
          env:
            - name: APPLICATION_HOSTNAME
              value: "{{ application_hostname }}"
      volumes:
        - name: pub-data
          persistentVolumeClaim:
            claimName: pub-data
