---
- name: 'Install Robottelo via pytest_project'
  include_role:
    name: pytest_project
    tasks_from: install
  vars:
    pytest_project_packages: "{{ robottelo_packages }}"
    pytest_project_url: "{{ robottelo_url }}"
    pytest_project_directory: "{{ robottelo_directory }}"
    pytest_project_requirements: "{{ robottelo_requirements }}"
    pytest_project_virtualenv_command: "{{ robottelo_virtualenv_command }}"
    pytest_project_version: "{{ robottelo_version }}"

- include_tasks: ssh.yml

- name: robottelo properties file
  command: cp robottelo.properties.sample robottelo.properties
  args:
    chdir: "{{ robottelo_directory }}"

- name: Set robottelo hostname
  ini_file:
    path: "{{ robottelo_directory }}/robottelo.properties"
    section: server
    option: hostname
    value: "{{ robottelo_hostname }}"

- name: Set robottelo SSH key
  ini_file:
    path: "{{ robottelo_directory }}/robottelo.properties"
    section: server
    option: ssh_key
    value: "{{ robottelo_ssh_key }}"

- name: Set robottelo SSH username
  ini_file:
    path: "{{ robottelo_directory }}/robottelo.properties"
    section: server
    option: ssh_username
    value: "{{ robottelo_ssh_username }}"

- name: Set robottelo logging
  replace:
    dest: "{{ robottelo_directory }}/logging.conf"
    regexp: "^level=DEBUG"
    replace: "level=INFO"

- name: 'Run Robottelo via pytest_project'
  include_role:
    name: pytest_project
    tasks_from: run
  vars:
    pytest_project_directory: "{{ robottelo_directory }}"
    pytest_project_junit_output: "{{ robottelo_junit_file }}"
    pytest_project_markers: "{{ robottelo_test_options[robottelo_test_type] | default(robottelo_test_options.default) }}"
    pytest_project_command_args: "{{ robottelo_test_path[robottelo_test_type] | default(robottelo_test_path.default) }}"
