- name: Make boostrap file executable
  file:
    dest: "{{ ansible_env.HOME }}/{{ customize_home_bootstrap_script }}"
    state: touch
    follow: false
    mode: a+x
  when: bootstrap_script_path.stat.exists

# The script is already on the machine, so using 'command' instead of 'script'. 'script' copies the script from the Ansible controller
- name: Run custom bootstrap script
  command: "{{ ansible_env.HOME }}/{{ customize_home_bootstrap_script }}"
  when: bootstrap_script_path.stat.exists

