---
- name: Create service
  k8s_v1_service:
      state: present
      force: false
      resource_definition:
          apiVersion: v1
          kind: Service
          metadata:
              name: foreman-proxy
              namespace: foreman
              labels:
                  app: foreman
                  service: foreman-proxy
          spec:
              selector:
                  app: foreman
                  service: foreman-proxy
              ports:
                - protocol: TCP
                  targetPort: 8080
                  name: port-8080-tcp
                  port: 8080
  tags:
    - start
