---
# You must restart the Rack server after changing either of these values
# because they are cached at startup.
#
:unattended: true
:login: true
:require_ssl: false
:locations_enabled: true
:organizations_enabled: true
:support_jsonp: false
:mark_translated: false
:admin_email: noreply@foreman.org
:loggers:
  :app:
    :enabled: true
  :ldap:
    :enabled: false
  :permissions:
    :enabled: false
  :sql:
    :enabled: false
:logging:
  :console_inline: true
  :level: info
:memcache:
  :hosts:
    - memcache
  :options:
    :namespace: foreman
    :expires_in: 86400
    :compress: true
