---
- name: Remove existing client-rpm job
  k8s_v1_job:
    state: absent
    namespace: foreman
    name: "client-rpm"
  tags:
    - destroy

- name: Create Job for client-rpm
  k8s_v1_job:
      state: "{{ deployment_state }}"
      resource_definition:
          apiVersion: batch/v1
          kind: Job
          metadata:
              name: client-rpm
              namespace: "{{ project_name }}"
              labels:
                  app: foreman
                  service: client-rpm
          spec:
              template:
                  metadata:
                      labels:
                          app: foreman
                          service: client-rpm
                  spec:
                      containers:
                        - name: client-rpm
                          securityContext: {}
                          state: present
                          volumeMounts:
                            - readOnly: true
                              mountPath: /etc/pki/katello/certs
                              name: certs
                            - readOnly: false
                              mountPath: /var/www/html/pub/
                              name: pub-data
                          command:
                            - ansible-playbook
                          args:
                            - build.yml
                          image: "{{ registry }}/foreman-client-rpm:latest"
                      serviceAccount: anyuid
                      serviceAccountName: anyuid
                      volumes:
                        - secret:
                              items:
                                - path: katello-default-ca.crt
                                  key: ca.crt
                              secretName: certs
                          name: certs
                        - name: pub-data
                          persistentVolumeClaim:
                              claimName: pub-data
                      restartPolicy: Never
  tags:
    - start
