- hosts: all
  become: true
  vars:
    katello_repositories_version: nightly
    katello_repositories_environment: staging
    foreman_repositories_version: nightly
    foreman_repositories_environment: staging
    puppet_repositories_version: 5
    foreman_installer_scenario: katello
    foreman_installer_additional_packages:
      - katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
      - "--katello-enable-ostree=true"
      - "--puppet-server-max-active-instances 1"
      - "--puppet-server-jvm-min-heap-size 1G"
      - "--puppet-server-jvm-max-heap-size 1G"
  roles:
    - umask
    - selinux
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - disable_firewall
    - haveged
    - swapfile
    - foreman_installer
    - foreman_testing
