---
- hosts: all
  become: true
  vars:
    server_repositories_katello: true
    server_repositories_ostree: true
    katello_repositories_version: nightly
    katello_repositories_environment: staging
    foreman_installer_scenario: katello-devel
    foreman_installer_additional_packages:
      - foreman-installer-katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--katello-devel-enable-ostree=true"
  roles:
    - etc_hosts
    - server_repositories
    - foreman_installer_devel_scenario
    - foreman_installer
