---
- hosts: server foreman-proxy-content
  become: true
  vars:
    foreman_server_repositories_katello: true
    foreman_server_repositories_ostree: true
    foreman_proxy_content_server_group: "server-{{ inventory_hostname }}"
    foreman_proxy_content_server: "{{ groups[foreman_proxy_content_server_group][0] }}"
  roles:
    - selinux
    - etc_hosts
    - foreman_server_repositories
    - foreman_proxy_content
    - role: foreman_installer
      foreman_installer_scenario: foreman-proxy-content
      foreman_installer_disable_system_checks: true
      foreman_installer_options_internal_use_only:
        - '--certs-tar-file "{{ foreman_proxy_content_certs_tar }}"'
        - '--foreman-proxy-content-enable-ostree true'
        - '--foreman-proxy-trusted-hosts "{{ server_fqdn }}"'
        - '--foreman-proxy-trusted-hosts "{{ ansible_nodename }}"'
        - '--foreman-proxy-foreman-base-url "https://{{ server_fqdn }}"'
        - '--foreman-proxy-register-in-foreman true'
        - '--foreman-proxy-oauth-consumer-key "{{ oauth_consumer_key }}"'
        - '--foreman-proxy-oauth-consumer-secret "{{ oauth_consumer_secret }}"'
        - "{{ '' if (foreman_repositories_version == 'nightly' or 2.3 is version(foreman_repositories_version, '>')) else ('--foreman-proxy-content-parent-fqdn %s' % server_fqdn) }}"
        - '--puppet-server-foreman-url https://"{{ server_fqdn }}"'
      foreman_installer_additional_packages:
          - foreman-installer-katello
