---
- import_playbook: katello_devel.yml
  vars:
    foreman_installer_options:
      - "--katello-devel-extra-plugins theforeman/foreman_discovery"
      - "--katello-devel-extra-plugins theforeman/foreman_ansible"
      - "--katello-devel-extra-plugins theforeman/foreman-tasks"
      - "--katello-devel-extra-plugins theforeman/foreman_bootdisk"
      - "--katello-devel-extra-plugins theforeman/foreman_openscap"
      - "--katello-devel-extra-plugins theforeman/foreman_templates"
      - "--katello-devel-extra-plugins theforeman/foreman_hooks"
