- hosts: localhost
  tasks:
    - name: 'Bring up box for Katello'
      command: vagrant up pipeline-katello-3.0-centos7

    - name: 'Bring up box for Capsule'
      command: vagrant up pipeline-capsule-3.0-centos7

    - name: 'Refresh inventory'
      meta: refresh_inventory

- hosts: pipeline-katello-3.0-centos7
  become: yes
  vars:
    katello_version: 3.0
    foreman_version: 1.11
    katello_repositories_use_koji: true
    foreman_installer_scenario: katello
    foreman_installer_options_internal_use_only:
      - "--disable-system-checks"
      - "--foreman-admin-password {{ foreman_installer_admin_password }}"
    foreman_installer_additional_packages:
      - katello
  roles:
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - foreman_installer

- hosts: pipeline-capsule-3.0-centos7
  become: yes
  vars:
    capsule_server: pipeline-katello-3.0-centos7
    katello_version: 3.0
    foreman_version: 1.11
    katello_repositories_use_koji: true
    foreman_installer_scenario: capsule
    foreman_installer_options_internal_use_only:
      - '--disable-system-checks
        --foreman-proxy-trusted-hosts "{{ server_fqdn.stdout }}"
        --foreman-proxy-trusted-hosts "{{ ansible_nodename }}"
        --foreman-proxy-foreman-base-url "https://{{ server_fqdn.stdout }}"
        --foreman-proxy-register-in-foreman true
        --foreman-proxy-oauth-consumer-key "{{ oauth_consumer_key.stdout }}"
        --foreman-proxy-oauth-consumer-secret "{{ oauth_consumer_secret.stdout }}"
        --capsule-certs-tar "{{ capsule_certs_tar }}"
        --capsule-parent-fqdn "{{ server_fqdn.stdout }}"
        --capsule-pulp-oauth-secret "{{ pulp_oauth_secret.stdout }}"'
    foreman_installer_additional_packages:
      - foreman-installer-katello
  roles:
    - etc_hosts
    - epel_repositories
    - puppet_repositories
    - foreman_repositories
    - katello_repositories
    - capsule
    - foreman_installer

- hosts: pipeline-katello-3.0-centos7
  become: true
  roles:
    - bats

- hosts: pipeline-capsule-3.0-centos7
  become: true
  vars:
    bats_tests:
      - fb-proxy.bats
  roles:
    - bats
